package capsule

// TaskState represents the final state of an archived task (e.g. "done" or "failed").
type TaskState string

const (
	StateDone   TaskState = "done"
	StateFailed TaskState = "failed"
)

// Capsule is the output document generated by rendering an archived task directory.
type Capsule struct {
	TaskID string    `json:"task_id"`
	State  TaskState `json:"state"`
	Text   string    `json:"text"`
}

// Unexported decode structs for parsing individual task artifacts read-only.
// Every field is optional so schema-drifted or partially present artifacts decode
// without error.

type specDoc struct {
	TaskID  string `yaml:"task_id"`
	Summary string `yaml:"summary"`
	Goal    string `yaml:"goal"`
}

type blueprintStep struct {
	Step   int      `yaml:"step"`
	Action string   `yaml:"action"`
	Files  []string `yaml:"files"`
}

type blueprintDoc struct {
	TaskID   string          `yaml:"task_id"`
	Summary  string          `yaml:"summary"`
	Strategy []blueprintStep `yaml:"strategy"`
}

type contractDoc struct {
	TaskID  string   `yaml:"task_id"`
	Summary string   `yaml:"summary"`
	Goal    string   `yaml:"goal"`
	Touch   []string `yaml:"touch"`
}

type validationCommand struct {
	Command  string `json:"command"`
	ExitCode int    `json:"exit_code"`
	Output   string `json:"output"`
	Error    string `json:"error"`
}

type validationDoc struct {
	TaskID        string              `json:"task_id"`
	OverallResult string              `json:"overall_result"`
	Commands      []validationCommand `json:"commands"`
}

type reviewFixTask struct {
	Slug  string `json:"slug"`
	Scope string `json:"scope"`
}

type reviewDoc struct {
	TaskID   string          `json:"task_id"`
	Summary  string          `json:"summary"`
	Verdict  string          `json:"verdict"`
	Notes    []string        `json:"notes"`
	FixTasks []reviewFixTask `json:"fix_tasks"`
}

type traceAttempt struct {
	Phase     string `json:"phase"`
	Result    string `json:"result"`
	Timestamp string `json:"timestamp"`
	Agent     string `json:"agent"`
	Model     string `json:"model"`
	Error     string `json:"error"`
}

type traceDoc struct {
	TaskID     string         `json:"task_id"`
	Violations []string       `json:"violations"`
	Attempts   []traceAttempt `json:"attempts"`
}
